### ISSUE TITLE
Cannot use arrow keys to scroll

### ISSUE THREAD

**Issue by paleyellowmoon** [aristidesfl/smoothkeyscroll#12]
I'm using Smooth Key Scroll 1.0.4 on Chrome 40.0.2214.91 m

Sometime in the past week or so, the arrow keys stopped working to scroll the web page.

I removed Smooth Key Scroll, and the arrow keys worked again.

I re-added Smooth Key Scroll, and the arrow keys stopped working.

**Comment by aristidesfl** [comment]
Which OS are you using?

**Comment by aristidesfl** [comment]
It seems it broke with chrome 40. Will post an update asap.

**Comment by aristidesfl** [comment]
1.0.5 should fix the problem and will be available in less than 60min in the store:
https://chrome.google.com/webstore/detail/smooth-key-scroll/gphmhpfbknciemgfnfhjapilmcaecljh

Let me know if it works and thank you for reporting this!
