### ISSUE TITLE
Gmail shortcuts stop working when using smoothkeyscroll in vim mode

### ISSUE THREAD

**Issue by MichaelAquilina** [aristidesfl/smoothkeyscroll#13]
Title pretty much sums it up. When using vim mode for navigation, the gmail shortcuts for navigating through the contents of your inbox stop working. Maybe we can add an appropriate rule to disable smooth scrolling in such a scenario?

**Comment by aristidesfl** [comment]
I'm considering between adding an editable blacklist of websites Smooth Key Scroll should be disabled or instead to try to fix manually the most popular websites like Gmail, etc.

**Comment by MichaelAquilina** [comment]
The blacklist feels like a quick solution. Maybe the manual fixes can follow as improvements after the blacklist has been realised?

**Comment by aristidesfl** [comment]
So, on inbox view we just disable smooth key scroll, simple.
But in the next release the mail view will be also scrollable with arrow keys. The question is what to do regarding vim keys, should they scroll the mail view or trigger gmail shortcuts to go to next email, back to inbox, etc?

**Comment by aristidesfl** [comment]
Version 2.2 fixes the gmail scrolling issue. The gmail shortcuts should not be disrupted, so scrolling with vi keys is disabled, however the arrow keys still work. 
Scrolling in the email view has been made smooth and also every other side with scrollable elements.

Test it out and let me know if it is working as expected, any feedback is appreciated.

**Comment by MichaelAquilina** [comment]
Just tested it out on gmail and it seems to be working for me so thanks for that :) The arrow keys dont seem to scroll though, they move through the items as normal gmail shortcuts. Is this as expected?

**Comment by aristidesfl** [comment]
Yes, when you are on the items view, no scroll is supposed to happen, otherwise it would be harder to read the items when you are moving the selection. Only when reading an email, you can scroll down.
