### ISSUE TITLE
Vi-like scroll keys

### ISSUE THREAD

**Issue by c00kiemon5ter** [aristidesfl/smoothkeyscroll#8]
Would it be possible to have j/k/h/l keys to scroll ?

Thanks

**Comment by selimekizoglu** [comment]
Any update on this?

**Comment by orschiro** [comment]
@selimekizoglu 

Have a look at Vimium which provides smooth scroll by default.

**Comment by aristidesfl** [comment]
I'm sorry, it will be released soon

**Comment by aristidesfl** [comment]
This has been added in v2.0

**Comment by orschiro** [comment]
@aristidesfl thank you for reporting back on this one! :+1:
